name = "RiemannSphereOperations"
uuid = "d30d4edc-727b-436c-a722-bc9a766de410"
authors = ["hyrodium <hyrodium@gmail.com> and contributors"]
version = "0.1.0"

[compat]
Aqua = "0.6"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Aqua"]
